{
 "title": "VSO Dashboard",
 "description": "Profiling performance-related metrics based on controller-runtime.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(controller_runtime_active_workers, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$Namespace\", service=\"$Service\"},  pod)"
    }
   },
   {
    "name": "Controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$Namespace\", service=\"$Service\", pod=\"$Pod\"},  controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vault Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault Authentication",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_resource_status{controller=\"vaultauth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_resource_status{controller=\"vaultconnection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reoncile Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (result) (rate(controller_runtime_reconcile_total{namespace=\"$Namespace\", service=\"$Service\", pod=\"$Pod\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{namespace=\"$Namespace\", service=\"$Service\", pod=\"$Pod\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller \"$Controller\" Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "Controller",
   "targets": [
    {}
   ]
  },
  {
   "title": "Reconcile Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{namespace=\"$Namespace\", service=\"$Service\", pod=\"$Pod\", controller=\"$Controller\"}[$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{namespace='$Namespace', service='$Service', pod='$Pod', controller='$Controller'}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}